export const SEND_SUCCESS = 'SEND_SUCCESS';
export const RECEIVE_SUCCESS = 'RECEIVE_SUCCESS';
export const SWITCH_LANGUAGE_SUCCESS = 'SWITCH_LANGUAGE_SUCCESS';
export const ADD_LENGTH = 'ADD_LENGTH';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';
