export default {
  messages: [],
  language: 'zh',
  languages: [
    {code:'zh', language:'中文'},
    {code:'en', language:'English'},
    {code:'yue', language:'粤语'},
    {code:'wyw', language:'文言文'},
    {code:'jp', language:'日本語'},
    {code:'kor', language:'한국어'},
    {code:'fra', language:'Français'},
    {code:'spa', language:'Español'},
    {code:'th', language:'ไทย'},
    {code:'ara', language:'العربية'},
    {code:'ru', language:'Русский язык'},
    {code:'pt', language:'Português'},
    {code:'de', language:'Deutsche Sprache'},
    {code:'it', language:'lingua italiana'},
    {code:'el', language:'Ελληνικά'},
    {code:'nl', language:'Nederlands'},
    {code:'pl', language:'Polski'},
    {code:'bul', language:'български'},
    {code:'est', language:'Eesti keel'},
    {code:'dan', language:'dansk'},
    {code:'fin', language:'suomalainen'},
    {code:'cs', language:'Česky'},
    {code:'rom', language:'românesc'},
    {code:'slo', language:'Slovenščina'},
    {code:'swe', language:'Svenska'},
    {code:'hu', language:'magyar'},
    {code:'cht', language:'繁體中文'},
    {code:'vie', language:'Người việt nam'}
  ],
  messageListLength: 1,
  user: {},
};
